version = 1

[[annotations]]
path = [
    "Ions.png",
    "Electrons.png",
    "examples/redcamel_data.h5",
]
SPDX-FileCopyrightText = "2025 Hannes Lindenblatt"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    "src/redcamel/icon.png",
]
SPDX-FileCopyrightText = "2026 Patrizia Schoch"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
    "pixi.lock",
    "uv.lock",
    ".github/workflows/*.yml",
    ".binder/workspace.json",
]
SPDX-FileCopyrightText = "2025 Hannes Lindenblatt"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "examples/scipp_example.ipynb",
    "examples/remicalculator.ipynb",
]
SPDX-FileCopyrightText = "2025 Hannes Lindenblatt"
SPDX-License-Identifier = " GPL-3.0-or-later"
